### ISSUE TITLE
Liquid syntax error (line 2): Unknown tag

### ISSUE THREAD

**Issue by deinsa** [jmfrenzel/documentation-theme-jekyll-multiple_language_pop#1]
Hi! I just downloaded the zip file containing the project. Whenever I try to run it, I get the following error: 

Liquid Exception: Liquid syntax error (line 2): Unknown tag 't' in /_layouts/page.html

I'm a complete noob on Jekyll, so I don't know what to do. I haven't changed anything on the site. I try to run It as it is. Can you please help me out on this? I'll really appreciate your help. 

Thanks. 

Andres

**Comment by kroschu** [comment]
Add this line to your application's Gemfile:

gem 'jekyll-multiple-languages-plugin'

and to _config.yml:
plugins:
  - jekyll-multiple-languages-plugin

And then execute: $ bundle install

**Comment by deinsa** [comment]
Hi kroschu. It worked! Thanks for your help :D
